# Generated by Django 3.1.3 on 2023-02-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=154, verbose_name='автор')),
                ('title', models.CharField(max_length=254, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('time_create', models.DateTimeField(verbose_name='Время Создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
